
## Background

Outcomes can take many forms and represent different things to different audiences. When used for planning, some forms of outcomes are more useful than others. The form of outcomes associated with OBP includes certain characteristics and qualities described here, which guide decisions and activities throughout the planning process.
For OBP, an outcome is a well-defined, observable, and measurable change in the existing situation that focuses on the end impact of those affected. It expresses changes as benefits, by improving capabilities within an organization or for its stakeholders.
An ideal outcome should have the following characteristics – 
1. Change – What are we changing? 
2. Affected Stakeholders – Who and what will it impact? 
3. Benefits – What are the benefits of the change?
4. Capability – What new or improved capabilities are required to make this change happen? Capabilities could be related to systems, manual processes, staff capabilities. etc.

Example: 
Improve provider satisfaction ratings by 15% within the next six months.
Characteristics of the above Outcome statement:
Change: Improve satisfaction with the Provider Enrollment approval timeline by providing additional interactive channels to resolve issues. (What is the goal?)
Affected Stakeholders: Providers, Provider Organization, State users, etc. (Whose need is it addressing?)
Benefits: Leads to quicker onboarding of providers, provider retention, and decreases state staff workload. (Why is it important?)
Capability: Might require an enhancement to redefine the Provider Enrollment process such as incorporating real-time updates to the workflow and adding interactive channels to provide real-time issue resolution. (How do you achieve it?)
