# SS-A Quick Reference Guide

## Introduction  
The SS-A Quick Reference Guide discusses the Medicaid IT Architecture (MITA) State Self-Assessment (SS-A) process. The SS-A is the state’s way to:  
- Review strategic goals and objectives.  
- Measure the maturity of business, information, and technical capabilities.  
- Develop target capabilities that allow transformation of its State Medicaid Enterprise.  
- Inform federal partners of the state’s strategic plans.  

The Centers for Medicare & Medicaid Services (CMS) expects all States to:  
- Complete/update the MITA SS-A within 12 months of the release of the MITA Framework 4.0.  
- Submit the SS-A as part of the Advance Planning Document (APD) process.  

## Purpose  
The purpose of conducting the SS-A is to identify the As-Is operations and To-Be environment of business, information, and technical capabilities of the State Medicaid Enterprise. Using standard methodologies and tools to document the way a state conducts business now, and intends to conduct business in the future, the SS-A facilitates alignment of the State Medicaid Enterprise to MITA Business, Information, and Technical Architectures (BA, IA, and TA), as well as the Enhanced Funding Requirements: Conditions and Standards.  

The SS-A will:  
- Provide a structured method for documenting and analyzing a state’s current Medicaid business enterprise.  
- Align SMA business areas to MITA business areas and business processes.  
- Enable the SMA to use defined levels of business maturity to help shape the future vision of its State Medicaid Enterprise.  
- Provide the foundation for a gap analysis that will support the state’s transition planning.  
- Facilitate the MITA Maturity Model Roadmap (MITA Roadmap).  
- Focus the APD to reflect current project funding requests and identify what is achievable.  

